### ISSUE TITLE
Using this code with Raspberry Pi

### ISSUE THREAD

**Issue by mhalamri** [keith-cullen/FreeCoAP#10]
Hello,
How can I upload this code to a Raspberry Pi 3?
I want to use the CoAP server test applications with CoAP/DTLS/IPv6 and using Cupper as a client.

Thanks,

**Comment by keith-cullen** [comment]
Build instructions in README.md will work on Raspberry PI. Alternatively you can set up a cross development environment on a laptop and copy the binary across to Raspberry PI.
