### ISSUE TITLE
problem implementing ipv6

### ISSUE THREAD

**Issue by kunavignesh** [keith-cullen/FreeCoAP#11]
Hello,
I am trying to run test_coap_server using the following commands,
make ip6=y dtls=n .
Successfully installed the required packages.
 Running on a Ubuntu 17.04 machine in a virtual box .
Getting an error : device or resource busy.
But on the specified port in the script no other processes are running.
How should we solve this?

**Comment by keith-cullen** [comment]
Add -g flag to CFLAGS in the Makefile. Run gdb. Step through the code and find out where the error ocurs.

**Comment by kunavignesh** [comment]
added the -g flag to the make file.
gdb was run .
got the following error
![screenshot from 2017-04-26 15-21-44](https://cloud.githubusercontent.com/assets/28016072/25436661/43531d0e-2a94-11e7-9592-eaf9ce3ca6fa.png)

**Comment by keith-cullen** [comment]
Break at main, run, step, find where the error is being returned.
