### ISSUE TITLE
unable to run test applications

### ISSUE THREAD

**Issue by shivatarun123** [keith-cullen/FreeCoAP#12]
I am running ubuntu 17.04 machine inside a virtual box 5.1.22.
I have created 6lowpan interfaces in separate namespaces using Linux fakelb modules.
I want to run test_coap_server applications on the 6lowpan interfaces which have been created.
I want to run the test_coap_client applications in the global namespace i.e. on the enp0s3 interface in my case.
I am able to run the server successfully without any errors on the 6lowpan interface but when I am running the test_client applications, the system hangs up and doesn't respond at all. I have waited for an hour and see no improvement.I have debugged both the applications, the client application hangs up at line 1292.
I wonder what's the problem?
can I solve this?
can the server run on the 6lowpan interface?

**Comment by shivatarun123** [comment]
We then tried using tiny DTLS and performed the tests specified as above. We were able to run 7 tests successfully but the VM freezes at the 8th test.        
Is there a solution??

**Comment by keith-cullen** [comment]
Have you changed the FreeCoAP code?
Try running individual tests, e.g. test_coap_client 1, test_coap_client 2, ...etc. See which one is the problem. Attach the console output.
Then step through the exchange function in test_coap_client.c with gdb.
Try building with DTLS disabled on the client and the server, e.g make dtls=n.

**Comment by shivatarun123** [comment]
No, I haven't changed the FreeCOAP code. I just updated the address of the lowpan interface instead of COAP server address both in the test server and test client applications. (i.e. at line:47 in test_coap_client.c and line:45 in test_coap_server.c)

I executed the tests individually and have noticed that 1-7 tests passed successfully whereas test 8 did not pass and the VM froze in that case.

I added a break to test_coap_client.c at line:924 and when tried to step through the code tests 1-7 had no problem in execution, while the VM froze during the execution of test 8. The code did not execute after breaking at the exchange function at line:934 in test_coap_client.c. I am attaching the screenshot of the same.

I have built with DTLS disabled on the client and the server as well. I could run all the tests successfully without any errors.

NOTE: I am performing the tests using FreeCOAP-tinydtls and not FreeCOAP-master. When I run master I could not run the tests at all enabling DTLS whereas I could successfully run all the tests disabling DTLS for the FreeCOAP-master. 
may I know how to solve the issue?
what are alternatives possible? (if any ) 
![whatsapp image 2017-05-05 at 17 09 45](https://cloud.githubusercontent.com/assets/28047693/25752511/d83b312e-31b8-11e7-9554-e4b783a1a3d7.jpeg)

**Comment by keith-cullen** [comment]
It looks like the DTLS handshake does not complete which is strange because it should time out. Are you using real hardware or pseudo devices? Can you tell me how to reproduce the problem?

**Comment by shivatarun123** [comment]
I am using virtual devices. I have created them using Linux network namespaces where each lowpan device runs in a different namespace and are connected to the border router which also is in a separate namespace. Forwarding is enabled in the border router. The border router is connected to the global namespace by a veth pair. Routes are added to reach the lowpan devices.(the devices are assigned ipv6 addresses.)

I want to run the coap_server on the lowpan devices and clients in the global namespace. When I tried to run FreeCOAP-master , I could not run even a single test and the system hanged but when I switched to FreeCOAP-tinydtls , I could run 7 tests and the machine froze after that as already mentioned.  

I am attaching the script and the scenario in which I am running the FreeCOAP applications by which you can reproduce the problem.

Install wpan tools using the following command:
sudo apt-get install wpan-tools.

Execute the included text file as shell script. 
After executing the script, add the route using the following command:
"ip route -6 add fd00:1::/64 via fd00:10::2 dev vpeer0".(execute as a superuser)


![img_4275](https://cloud.githubusercontent.com/assets/28047693/25772812/0245d158-3273-11e7-905c-7af58b370afc.JPG)
[test_bed.txt](https://github.com/keith-cullen/FreeCoAP/files/980961/test_bed.txt)

**Comment by keith-cullen** [comment]
Which IP address do you give to the client and server?

**Comment by shivatarun123** [comment]
The server runs on the lowpan device in the namespace ns:wpan1 and its IP address fd00:1::10 and the client runs in the global namespace.

**Comment by keith-cullen** [comment]
It works for me on a real Linux machine running Fedora 24, kernel v4.8.13.
Do I need to call setns in the server?

**Comment by shivatarun123** [comment]
We are running on ubuntu 17.04 kernel version 4.10.0 in virtual box.
No, you don't need to call setns on the server because we are directly executing the server in namespace wpan1 using the command: 
sudo ip netns exec wpan1 bash
