### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by shivatarun123** [keith-cullen/FreeCoAP#13]
When I tried to run the test_http_client with the proxy. I noticed that the tests have passed successfully. When  I observe the data between the client and proxy using Wireshark, there are no TLS packets between client and proxy but between the proxy and COAP server, there are DTLS packets. 

Do I need to do anything to enable TLS on HTTP side?
I have tried the same with tinydtls also but there are no TLS packets between the client and proxy.

I followed the instructions provided in the readme.md to test HTTP/CoAP proxy application with HTTP/TLS/IPv6 and CoAP/DTLS/IPv6

**Comment by keith-cullen** [comment]
try:
tcpdump -i lo port 12437 -w out.pcap
you will see TLS packets.
