### ISSUE TITLE
Test on Intel Galileo Gen 1

### ISSUE THREAD

**Issue by smnd90** [keith-cullen/FreeCoAP#14]
I want to try FreeCoAP (client only) on Intel Galileo Gen 1 (I saw that you test it). How to install GnuTLS on this board? Any other dependencies?
Or is necessary a cross compilation?
Thanks

**Comment by keith-cullen** [comment]
I downloaded the BSP:
Board_Support_Package_Sources_for_Intel_Quark_v1.2.0.7z
Extract, yocto from the BSP, setup and build.
Use yocto to build the toolchain.
Create a root filesystem on your host machine.
Cross compile coap code on your host machine.

Note: do not try to cross compile the proxy. Galileo has a hardware bug called 'lock prefix' that is triggered by the pthreads library which is used by the proxy.

**Comment by smnd90** [comment]
Wow. Thanks. Have you a link to online tutorial that explain this process? Anyway, thank a lot

**Comment by smnd90** [comment]
I managed to download Yocto and make a cross-compilation with a simple "Hello World" on Galileo. But if I wanted to compile FreeCoAP, how can I insert GnuTLS between the dependences? Do you have a sample Makefile? I do not understand if it's enough that I have installed GnuTLS on my PC or if I have to install it elsewhere.
