### ISSUE TITLE
proxy applications

### ISSUE THREAD

**Issue by shivatarun123** [keith-cullen/FreeCoAP#16]
How to proxy test applications without TLS/DTLS support?
How to run proxy test application with TLS on the side and without DTLS on the other side?

**Comment by keith-cullen** [comment]
TLS/DTLS is used everywhere in the proxy to minimise the amount of testing required.

HTTP side always uses TLS. This cannot be changed without rewriting the code.
On CoAP side, DTLS can be disabled by removing -DCOAP_DTLS_EN from proxy Makefile, replacing the call to coap_client_create in proxy/http_coap/src/connection.c with non-DTLS version (see coap_client.h), and building test_coap_server with dtls=n option.
