### ISSUE TITLE
Disabling DTLS on COAP side in proxy applications

### ISSUE THREAD

**Issue by shivatarun123** [keith-cullen/FreeCoAP#17]
Hi
I have removed a DCOAP_DTLS_EN flag from the proxy make file and bullied the test_coap_server with dtls=n.   But when I tried to build the proxy I got the following error:
"too many arguments to the function coap_client_create"
 Can you please say what changes should  I need to do in order to replace  call to coap_client_create in proxy/http_coap/src/connection.c with non-DTLS version

**Comment by keith-cullen** [comment]
replace:

ret = coap_client_create(&con->coap_client,
                        uri_get_host(uri),
                        uri_get_port(uri),
                        param_get_coap_client_key_file_name(con->param),
                        param_get_coap_client_cert_file_name(con->param),
                        param_get_coap_client_trust_file_name(con->param),
                        NULL,
                        NULL);

with:

ret = coap_client_create(&con->coap_client,
                        uri_get_host(uri),
                        uri_get_port(uri));
