### ISSUE TITLE
I have some question about how to build your proxy code

### ISSUE THREAD

**Issue by ejkim14** [keith-cullen/FreeCoAP#2]
Hello,
I have some question about your code 'HTTP/CoAP proxy application with TLS and DTLS'.
I put the "make" commnad in 'test coap server folder'(../test/test_coap_server)
and some error occured in terminal like below.

-----------------------------------------------------------------------------------------------
../test/test_coap_server# make
gcc  test_coap_server.o coap_server.o coap_msg.o coap_log.o -o test_coap_server -lgmp -lhogweed -lnettle -lgnutls
coap_server.o: In function `coap_server_trans_dtls_create':
/root/CoAP-P/test/test_coap_server/../../lib/src/coap_server.c:429: undefined reference to `gnutls_transport_set_pull_timeout_function'
/root/CoAP-P/test/test_coap_server/../../lib/src/coap_server.c:431: undefined reference to `gnutls_dtls_set_mtu'
/root/CoAP-P/test/test_coap_server/../../lib/src/coap_server.c:432: undefined reference to `gnutls_dtls_set_timeouts'
collect2: error: ld returned 1 exit status
make: *** [test_coap_server] Error 1
-----------------------------------------------------------------------------------------------
I tried to find some info related to error like gnutls. but i couldn't soleve that problem..
if you know how to solve this problem. plz give some commnets for me
Thanks in advance.

**Comment by keith-cullen** [comment]
You need to have the development version of GnuTLS installed.
Depending on your distribution, the command to install GnuTLS is one of the
following:

Ubuntu:
sudo apt-get install libgnutls-dev

Fedora version <22:
sudo yum install gnutls-devel

Fedora version >=22:
sudo dnf install gnutls-devel

**Comment by ejkim14** [comment]
Ok.. I already installed libgnutls-dev package. But, still occured same error. ㅜ.ㅜ

**Comment by keith-cullen** [comment]
Ok, so the error message is coming from the linker. You need to make sure
the linker can find libgnutls.

Step 1. Find libgnutls

whereis libgnutls

Step 2. Add the path to libgnutls to the linker search path

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path-to-libgnutls>

(replace <path-to-libgnutls> above with the result of step 1)

e.g.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
