### ISSUE TITLE
function coap_server_get_resp_type have a bug

### ISSUE THREAD

**Issue by leon0625** [keith-cullen/FreeCoAP#20]
when uri is "/22222/123", this function can't match, the buf is "/22222/12322".
patch:
```diff
Index: free_coap_lib/src/coap_server.c
===================================================================
--- free_coap_lib/src/coap_server.c	(revision 931)
+++src/coap_server.c	(working copy)
@@ -1831,6 +1831,11 @@
     {
         buf[0] = '/';
     }
+    else
+    {
+        *p = '\0';
+    }
+    printf("[llm] %s(%d)buf = %s\n", __FUNCTION__, __LINE__, buf);
     match = coap_server_path_list_match(&server->sep_list, buf);
     return match ? COAP_SERVER_SEPARATE : COAP_SERVER_PIGGYBACKED;
 }
```

**Comment by keith-cullen** [comment]
Bug is there but your fix is wrong. Correct fix is:

diff --git a/lib/src/coap_server.c b/lib/src/coap_server.c
index 41ea268..3fef576 100755
--- a/lib/src/coap_server.c
+++ b/lib/src/coap_server.c
@@ -1819,6 +1819,7 @@ static int coap_server_get_resp_type(coap_server_t *server, coap_msg_t *msg)
             if (val_len > sizeof(val_buf) - 1)
                 val_len = sizeof(val_buf) - 1;
             memcpy(val_buf, val, val_len);
+            memset(val_buf + val_len, 0, sizeof(val_buf) - val_len);
             strncpy(p, val_buf, len);
             add = (val_len < len) ? val_len : len;
             p += add;

**Comment by keith-cullen** [comment]
Bug is there but your fix is wrong. Correct fix is:

```diff
diff --git a/lib/src/coap_server.c b/lib/src/coap_server.c
index 41ea268..3fef576 100755
--- a/lib/src/coap_server.c
+++ b/lib/src/coap_server.c
@@ -1819,6 +1819,7 @@ static int coap_server_get_resp_type(coap_server_t *server, coap_msg_t *msg)
             if (val_len > sizeof(val_buf) - 1)
                 val_len = sizeof(val_buf) - 1;
             memcpy(val_buf, val, val_len);
+            memset(val_buf + val_len, 0, sizeof(val_buf) - val_len);
             strncpy(p, val_buf, len);
             add = (val_len < len) ? val_len : len;
             p += add;
