### ISSUE TITLE
running failed under mips system

### ISSUE THREAD

**Issue by codegandlg** [keith-cullen/FreeCoAP#28]
I tested it under Ubuntu system ,the programming generate client application,it works well under Ubuntu system .
but ,when porting this program to mips CPU(base on Linux 2.6 kernel),encounted error as below:
/usr/sbin/client: line 1: syntax error: unexpected word (expecting ")")

to check  executable program formate  by file command:
#file client 
client: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0xf6825841efc4c945b433e12929202a3879bd2b40, not stripped

so the probem is that my hardware is MIPS ,but the generated excutable application is Inter 80386,how can let this code works on MIPS system? 
 here is another formate excutable application as bellow:
#file appMng
appMng: ELF 32-bit MSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked (uses shared libs), with unknown capability 0x41000000 = 0xf676e75, with unknown capability 0x10000 = 0x70403, stripped
it works well on my MIPS system

**Comment by codegandlg** [comment]
running under Inter80386(linux system):
![02](https://user-images.githubusercontent.com/9245324/33105889-7c23ec82-cf6a-11e7-95db-ef47a1c8b9be.png)

MIPS(linux system)
![01](https://user-images.githubusercontent.com/9245324/33105930-a5a5c396-cf6a-11e7-9b5b-84ad5740c8bf.png)

**Comment by keith-cullen** [comment]
Mips is not supported. If you are cross compiling on an x86 host for a mips target then you need to modify the Makefiles to use the mips toolchain and sysroot.
