### ISSUE TITLE
Piggy-backed response

### ISSUE THREAD

**Issue by DvdSpijker** [keith-cullen/FreeCoAP#29]
Hi Keith,
I'm having problems attaching a payload to an Ack message i.e. a piggy-backed response. When checking the coap_server_exchange function I cannot find the lines that set the payload for the Ack.
Can you please tell how I can achieve this?
Kind regards,
Dorus

**Comment by keith-cullen** [comment]
Setting the payload is done using: coap_msg_set_payload(coap_msg_t *msg, char *buf, size_t len)

This should be called from your application in your coap_server_handler_t call-back function. You register a coap_server_handler_t function when you create a CoAP server.

The coap_server_handler_t function is given a resp argument than represents the CoAP response. This can be a piggy-backed response or a separate response but you don't need to differentiate between the two.

Look at reg_server_handle() in sample/reg_server/reg_server.c for an example.
