### ISSUE TITLE
How can I solve the bi-directional problem?

### ISSUE THREAD

**Issue by louisZL** [keith-cullen/FreeCoAP#4]
When the device is behind NAT/firewall, we should keep the route alive.
How can we do that? How can we solve the bi-directional problem?
The device should be a server and a client, and they should share the same address and port.

**Comment by keith-cullen** [comment]
FreeCoAP was specifically designed to use IPv6 which is the standard
network protocol for IoT.
IPv6 eliminates the need for NAT. If you want to use protocols like CoAP
(and SIP for example)
behind NAT then you might need to employ additional protocols such as ICE
or STUN.

With regards to the firewall issue. I am planning to update the proxy so
that it keeps transactions
with the coap server open for as long as possible. This will avoid the need
to perform a DTLS
handshake for every request/response. I am not sure it will solve your
problem though.

It seems as though you are interested primarily in an IPv4 solution which
is not what I had in mind.
I don't plan to support IPv4 in my implementation.

Keith.

**Comment by keith-cullen** [comment]
The HTTP/CoAP proxy now supports IPv4 and IPv6. The proxy now keeps transactions with the coap server open for as long as possible.
