### ISSUE TITLE
The peer certificate is not trusted

### ISSUE THREAD

**Issue by sheraz045** [keith-cullen/FreeCoAP#7]
sheraz@sheraz-VirtualBox:~/Desktop/FreeCoAP-master/test/test_proxy_http_coap$ ./proxy
Notice : reading config file: 'proxy.conf'
Notice : config parameter: 'port'='12437'
Notice : config parameter: 'log_level'='debug'
Notice : config parameter: 'key_file'='../../certs/server_privkey.pem'
Notice : config parameter: 'cert_file'='../../certs/server_cert.pem'
Notice : config parameter: 'trust_file'='../../certs/root_client_cert.pem'
Notice : config parameter: 'key_file'='../../certs/client_privkey.pem'
Notice : config parameter: 'cert_file'='../../certs/client_cert.pem'
Notice : config parameter: 'trust_file'='../../certs/root_server_cert.pem'
Notice : finished reading config file: 'proxy.conf'
Notice : Proxy running
Notice : [0] Listening on port 12437
Notice : [0] <0> 127.0.0.1 Connection with HTTP client started
Notice : [0] <0> 127.0.0.1 Transaction with HTTP client started
Error  : [0] <0> 127.0.0.1 Failed to read from socket connected to HTTP client: unable to read from socket
Notice : [0] <0> 127.0.0.1 Transaction with HTTP client failed
Notice : [0] <0> 127.0.0.1 Connection with HTTP client failed
Info   : OK connections:      0
Info   : Failed connections:  1
Info   : OK transactions:     0
Info   : Failed transactions: 1

./test_http_client 1

----------------------------------------
test 1: Send GET request
Error  : The peer certificate is not trusted
*****************[FAIL]*****************

[Total: 1, Pass: 0, Fail: 1]

**Comment by keith-cullen** [comment]
Please pull the latest code, rerun the test and report the GnuTLS version you are using.

**Comment by sheraz045** [comment]
i pulled the latest code but still have the same issue 
GnuTLS version 3.3.15
![12](https://cloud.githubusercontent.com/assets/15107481/19941012/8564f632-a154-11e6-96e2-8116b86225a6.jpg)

**Comment by keith-cullen** [comment]
I was able to repeat the issue with GnuTLS version 3.5.5. It only occurs with newer versions of GnuTLS (i.e. greater than version 3.2.0). As a work-around you can comment out the return statement on line 330 in proxy/common/src/tls_sock.c.

    if (status & GNUTLS_CERT_INVALID)
    {
        coap_log_error("The peer certificate is not trusted");
//        return SOCK_PEER_CERT_VERIFY_ERROR;    // comment out this line to work around the issue
    }

I will investigate further in the mean-time.

**Comment by keith-cullen** [comment]
Should be fixed now. Let me know if it works for you. Thanks for reporting the issue.
