### ISSUE TITLE
Proxy selection

### ISSUE THREAD

**Issue by sheraz045** [keith-cullen/FreeCoAP#8]
How do you select forward or reverse proxy node in the FreeCoAP
Is it pre-selected or  dynamically choosen

**Comment by keith-cullen** [comment]
The proxy is a HTTP/CoAP cross-protocol forward proxy.

A HTTP client sends a HTTP request message to the proxy's TCP address and port number but the message contains a Request-URI that belongs to the CoAP origin server. In other words the HTTP client knows it is accessing a CoAP origin server through an intermediary. e.g.

GET coaps://[::1]:12436/resource HTTP/1.1
